// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestDevCore.Infrastructure.Persistence.DomainModel;

#nullable disable

namespace TestDevCore.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DomainDbContext))]
    [Migration("20260615012748_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestDevCore.Domain.Accounts.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Holder")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("TestDevCore.Domain.Currencies.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("Symbol");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("TestDevCore.Domain.ExchangeRates.Entities.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SymbolBase")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SymbolTarget")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SymbolBase", "SymbolTarget")
                        .IsUnique()
                        .HasDatabaseName("IX_ExchangeRates_SymbolBase_SymbolTarget");

                    b.ToTable("ExchangeRates", (string)null);
                });

            modelBuilder.Entity("TestDevCore.Domain.Movements.Entities.Movement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Movements", (string)null);
                });

            modelBuilder.Entity("TestDevCore.Domain.Movements.Entities.MovementDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MovementId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("MovementId");

                    b.HasIndex("MovementId1");

                    b.ToTable("MovementDetails", (string)null);
                });

            modelBuilder.Entity("TestDevCore.Domain.Accounts.Entities.Account", b =>
                {
                    b.HasOne("TestDevCore.Domain.Currencies.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TestDevCore.Domain.Accounts.ValueObjects.AmountVO", "Balance", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Balance");

                            b1.HasKey("AccountId");

                            b1.ToTable("Accounts");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("Balance")
                        .IsRequired();
                });

            modelBuilder.Entity("TestDevCore.Domain.Movements.Entities.Movement", b =>
                {
                    b.OwnsOne("TestDevCore.Domain.Accounts.ValueObjects.AmountVO", "ExchangeRate", b1 =>
                        {
                            b1.Property<Guid>("MovementId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ExchangeRate");

                            b1.HasKey("MovementId");

                            b1.ToTable("Movements");

                            b1.WithOwner()
                                .HasForeignKey("MovementId");
                        });

                    b.Navigation("ExchangeRate")
                        .IsRequired();
                });

            modelBuilder.Entity("TestDevCore.Domain.Movements.Entities.MovementDetail", b =>
                {
                    b.HasOne("TestDevCore.Domain.Accounts.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestDevCore.Domain.Movements.Entities.Movement", null)
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestDevCore.Domain.Movements.Entities.Movement", null)
                        .WithMany("MovementDetails")
                        .HasForeignKey("MovementId1");

                    b.OwnsOne("TestDevCore.Domain.Accounts.ValueObjects.AmountVO", "Amount", b1 =>
                        {
                            b1.Property<Guid>("MovementDetailId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.HasKey("MovementDetailId");

                            b1.ToTable("MovementDetails");

                            b1.WithOwner()
                                .HasForeignKey("MovementDetailId");
                        });

                    b.OwnsOne("TestDevCore.Domain.Accounts.ValueObjects.AmountVO", "NewBalance", b1 =>
                        {
                            b1.Property<Guid>("MovementDetailId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("NewBalance");

                            b1.HasKey("MovementDetailId");

                            b1.ToTable("MovementDetails");

                            b1.WithOwner()
                                .HasForeignKey("MovementDetailId");
                        });

                    b.OwnsOne("TestDevCore.Domain.Accounts.ValueObjects.AmountVO", "PreviousBalance", b1 =>
                        {
                            b1.Property<Guid>("MovementDetailId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PreviousBalance");

                            b1.HasKey("MovementDetailId");

                            b1.ToTable("MovementDetails");

                            b1.WithOwner()
                                .HasForeignKey("MovementDetailId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("NewBalance")
                        .IsRequired();

                    b.Navigation("PreviousBalance")
                        .IsRequired();
                });

            modelBuilder.Entity("TestDevCore.Domain.Movements.Entities.Movement", b =>
                {
                    b.Navigation("MovementDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
